# Generated by Django 2.0.12 on 2020-02-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Andznakazm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=32, verbose_name='FirstName')),
                ('LastName', models.CharField(max_length=32, verbose_name='LastName')),
                ('Kochum', models.CharField(max_length=32, verbose_name='kochum')),
            ],
        ),
    ]
